    {{WORKLOAD_NAME}}-{{CONTAINER}}:
        entrypoint: ["/entrypoint.sh"]
        volumes:
        - type: bind
            source: {{ABSOLUTE_PATH_TO_ENTRYPOINT_SH}}\entrypoint_dotnet_external.sh
            target: /entrypoint.sh